import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import {useResource,ResourceState} from '../components/ContentUI';
import {MarkdownContent} from '../components/MarkdownContent';
import '../../styles/blog-foundation.css';
type Social={name:string;url:string;enabled:boolean};type Friend=Social&{description:string;icon:string};type Form={about:{enabled:boolean;name:string;intro:string;avatar:string;content:string;social:Social[]};links:Friend[]};
export default function AdminBlogPages(){const resource=useResource<Form>('/settings/blog-pages/manage');const [form,setForm]=useState<Form|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');useEffect(()=>{if(resource.data)setForm(resource.data);},[resource.data]);
 function about(key:string,value:unknown){setForm(f=>f?{...f,about:{...f.about,[key]:value}}:f);}
 function change(kind:'links'|'social',index:number,key:string,value:unknown){if(!form)return;const list=kind==='links'?form.links:form.about.social;const next=list.map((x,i)=>i===index?{...x,[key]:value}:x);if(kind==='links')setForm({...form,links:next as Friend[]});else about('social',next);}
 function move(kind:'links'|'social',index:number,delta:number){if(!form)return;const list=[...(kind==='links'?form.links:form.about.social)];if(index+delta<0||index+delta>=list.length)return;[list[index],list[index+delta]]=[list[index+delta],list[index]];if(kind==='links')setForm({...form,links:list as Friend[]});else about('social',list);}
 function remove(kind:'links'|'social',index:number){if(!form)return;if(kind==='links')setForm({...form,links:form.links.filter((_,i)=>i!==index)});else about('social',form.about.social.filter((_,i)=>i!==index));}
 async function save(){if(!form||busy)return;setBusy(true);setMessage('');try{await api('/settings/blog-pages',{method:'PUT',body:JSON.stringify(form)});setMessage('已保存，公开页面已更新。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="blog-pages-editor"><h1>关于与友链</h1><p className="muted">维护公开介绍、社交链接和友情链接。</p><ResourceState resource={resource}>{form&&<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><legend>关于我</legend><label><input type="checkbox" checked={form.about.enabled} onChange={e=>about('enabled',e.target.checked)}/>公开介绍</label>{[['name','名称'],['intro','简介'],['avatar','头像地址']].map(([key,label])=><label key={key}>{label}<input value={String(form.about[key as keyof typeof form.about])} onChange={e=>about(key,e.target.value)}/></label>)}<label>正文（Markdown）<textarea rows={10} value={form.about.content} onChange={e=>about('content',e.target.value)}/></label><details><summary>预览介绍正文</summary><MarkdownContent content={form.about.content}/></details>
 {(['social','links'] as const).map(kind=>{const list=kind==='social'?form.about.social:form.links;return <section key={kind}><h2>{kind==='social'?'社交链接':'友情链接'}</h2>{list.map((row,i)=><fieldset className="blog-link-editor" key={i}><legend>{kind==='social'?'社交链接':'友链'} {i+1}</legend>{(kind==='social'?['name','url']:['name','url','description','icon']).map(key=><label key={key}>{({name:'名称',url:'网址',description:'简介',icon:'图标地址'} as Record<string,string>)[key]}<input required={key==='name'||key==='url'} type={key==='url'?'url':'text'} value={String((row as any)[key]||'')} onChange={e=>change(kind,i,key,e.target.value)}/></label>)}<label><input type="checkbox" checked={row.enabled} onChange={e=>change(kind,i,'enabled',e.target.checked)}/>公开显示</label><div className="inline-actions"><button type="button" disabled={i===0} onClick={()=>move(kind,i,-1)}>上移</button><button type="button" disabled={i===list.length-1} onClick={()=>move(kind,i,1)}>下移</button><button type="button" onClick={()=>remove(kind,i)}>移除</button></div></fieldset>)}<button type="button" className="quiet-button" disabled={list.length>=(kind==='social'?20:100)} onClick={()=>kind==='social'?about('social',[...list,{name:'',url:'',enabled:true}]):setForm({...form,links:[...form.links,{name:'',url:'',description:'',icon:'',enabled:true}]})}>添加{kind==='social'?'社交链接':'友链'}</button></section>;})}
 <button className="quiet-button" type="submit">{busy?'正在保存…':'保存设置'}</button></fieldset><p role="status">{message}</p></form>}</ResourceState></section>;
}
