import {MailFailureTasks} from '../components/MailFailureTasks';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Inbox,CalendarClock,TriangleAlert,ArrowUpRight,BarChart3} from 'lucide-react';
import {api} from '../lib/api';
import '../../styles/account-operations.css';
export default function OperationsPage(){
 const [query,setQuery]=useState('days=30'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const load=async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const r=await api('/admin/operations?'+query,{signal});if(!signal?.aborted)setData(r);}catch(e:any){if(!signal?.aborted)setError(e.message);}finally{if(!signal?.aborted)setLoading(false);}};
 useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>c.abort();},[query]);
 const cards=data?[{name:'待审投稿',value:data.summary.pending,to:'/admin/reviews',icon:Inbox},{name:'发布计划',value:data.summary.scheduled,to:'/admin/schedules',icon:CalendarClock},{name:'发布失败',value:data.summary.failed,to:'/admin/schedules?state=failed',icon:TriangleAlert}]:[];
 return <section className="operations-page"><header className="workspace-heading"><div><span className="workspace-eyebrow">内容运营</span><h1>运营概览</h1><p>先处理发布待办，再看文章的阅读与互动。</p></div><Link className="operations-text-link" to="/admin/analytics">完整访问统计 <ArrowUpRight size={15}/></Link></header>
 {error&&<p className="workspace-alert" role="alert">{error}<button onClick={()=>void load()}>重试</button></p>}
 <div className="operations-tasks">{cards.map(c=><Link to={c.to} className="operations-task" key={c.name}><span><c.icon size={18}/>{c.name}</span><strong>{c.value}</strong><small>查看并处理 →</small></Link>)}</div>
 <section className="operations-panel"><div className="operations-panel-title"><h2>阅读与互动</h2><div className="operations-period" aria-label="统计周期">{[7,30,90].map(n=><button key={n} aria-pressed={query==='days='+n} onClick={()=>setQuery('days='+n)}>近 {n} 天</button>)}</div></div>
 <form className="operations-range" onSubmit={e=>{e.preventDefault();setQuery('from='+from+'&to='+to);}}><label>开始日期<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>结束日期<input type="date" required value={to} onChange={e=>setTo(e.target.value)}/></label><button className="engagement-button" disabled={loading}>应用日期</button><span>按 UTC 日期统计，最长 90 天</span></form>
 {loading?<div className="workspace-empty" role="status">正在加载运营数据…</div>:data&&<><div className="operations-metrics"><div><span>文章阅读</span><strong>{data.summary.views}</strong><small>{data.start} — {data.end}</small></div><div><span>公开评论</span><strong>{data.summary.comments}</strong><small>区间内创建、目前仍公开</small></div><div><span>收藏 · 当前总量</span><strong>{data.summary.bookmarks}</strong><small>所有现存收藏，含已下架文章</small></div></div>
 <div className="operations-chart-label"><span>每日文章阅读 · 次</span><span>最高 {Math.max(0,...data.trend.map((x:any)=>x.views||0))}</span></div><div className="operations-trend" role="img" aria-label="每日文章阅读量；具体数值可展开数据表查看">{data.trend.map((d:any)=><div key={d.day} title={d.day+'：'+(d.views===null?'未采集':d.views+' 次阅读')} className={d.views===null?'is-missing':''}><span style={{height:d.views===null?'12%':Math.max(2,d.views/Math.max(1,...data.trend.map((x:any)=>x.views||0))*100)+'%'}}/></div>)}</div>
 <div className="operations-chart-label"><span>{data.start}</span><span>{data.end}</span></div><p className="operations-note">阅读沿用现有 30 秒去重口径，排除管理员、机器人和 DNT 请求。{data.partial?'所选范围包含未采集日期，图中以斜线标记，不计为零。':'所选范围位于已有统计区间。'}收藏未采集历史快照，无法提供历史新增量。</p>
 <details className="operations-daily"><summary>查看每日阅读数据</summary><div>{data.trend.map((d:any)=><p key={d.day}><span>{d.day}</span><strong>{d.views===null?'未采集':d.views}</strong></p>)}</div></details></>}
 </section>
 {data&&<><section className="operations-panel"><div className="operations-panel-title"><h2>文章阅读排行</h2><span>最多显示 20 篇公开文章</span></div>{!data.articles.length?<div className="workspace-empty"><BarChart3/><h2>还没有公开文章</h2></div>:<div className="operations-table-wrap"><table><thead><tr><th>文章</th><th>区间阅读</th><th>区间公开评论</th><th>当前收藏</th></tr></thead><tbody>{data.articles.map((p:any)=><tr key={p.id}><td><Link to={'/article/'+p.id}>{p.title}</Link></td><td data-label="区间阅读">{p.views}</td><td data-label="区间公开评论">{p.comments}</td><td data-label="当前收藏">{p.bookmarks}</td></tr>)}</tbody></table></div>}</section>
 <section className="operations-panel"><div className="operations-panel-title"><h2>需要处理</h2><span>当前状态，不受日期筛选影响</span></div>{data.tasks.length?data.tasks.map((t:any)=><Link className="operations-todo" to={(t.state==='submitted'?'/admin/reviews':'/admin/schedules')+'?state='+t.state} key={t.draft_id}><div><strong>{t.title||'未命名稿件'}</strong>{t.reason&&<p>{t.reason}</p>}{t.scheduled_at&&<p>北京时间 {new Date(Number(t.scheduled_at)).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>}</div><span>{t.state==='failed'?'发布失败':t.state==='submitted'?'待审核':'待发布'} →</span></Link>):<div className="workspace-empty"><Inbox/><h2>目前没有发布待办</h2><p>新的投稿和排期会显示在这里。</p></div>}
 <MailFailureTasks count={data.summary.mailFailed} onQueued={()=>void load()}/></section></>}
 </section>;
}