const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),esbuild=require('esbuild');
const code=esbuild.transformSync(require('node:fs').readFileSync('src/app/lib/browserDiagnostics.ts','utf8'),{loader:'ts',format:'cjs',define:{'import.meta.env.VITE_BUILD_REVISION':'"test-build"'}}).code;
function load(saved){const store=new Map(saved?[['mooncci.diagnostics.v1',JSON.stringify(saved)]]:[]);let time=100000;const context={module:{exports:{}},exports:{},Date:class extends Date{static now(){return time;}},setTimeout:()=>1,clearTimeout:()=>{},performance:{now:()=>time},sessionStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}};vm.runInNewContext(code,context);return {api:context.module.exports,store,tick:()=>time+=21*60*1000};}
test('diagnostics default off, whitelist drops private paths and query strings',()=>{const{api}=load();assert.equal(api.beginApiDiagnostic('/posts?token=private'),null);assert.equal(api.diagnosticPath('/api/posts/12?secret=hide'),'/api/posts/:id');assert.equal(api.diagnosticPath('/api/mailboxes/credentials/reveal'),null);assert.equal(api.diagnosticPath('/api/search?query=private'),null);assert.equal(api.diagnosticPath('https://attacker.invalid/api/posts'),null);assert.equal(api.diagnosticPath('/api/mailboxes/folders/inbox/15?uidValidity=99'),'/api/mailboxes/folders/inbox/:uid');});
test('opt-in measures requests without response payloads or untrusted headers, cap 500',()=>{const{api}=load();api.startDiagnostics('relay-on');for(let i=0;i<510;i++){const task=api.beginApiDiagnostic('/posts?search=private');task.response(new Response('secret-body',{headers:{'X-Diagnostic-Request-ID':'secret-token','X-Diagnostic-Ingress':'SECRET','Server-Timing':'app;dur=12.5'}}));task.finish();}const report=JSON.parse(api.exportDiagnostics());assert.equal(report.rows.length,500);assert.equal(report.rows[0].api_ms,12.5);assert.equal(report.rows[0].request_id,'');assert.equal(report.rows[0].ingress,'UNKNOWN');assert(!JSON.stringify(report).includes('secret'));api.stopDiagnostics();assert.equal(api.beginApiDiagnostic('/posts'),null);});
test('expiry stops collection and clear erases stored report',()=>{const{api,tick,store}=load();api.startDiagnostics('relay-off');tick();assert.equal(api.diagnosticsActive(),false);api.clearDiagnostics();assert.equal(store.size,0);});
test('reload restores only sanitized metadata and rejects expired reports',()=>{const saved={version:1,started:99000,expires:200000,active:false,mode:'unknown',rows:[{type:'api',path:'/api/posts/20?secret=x',password:'secret',request_id:'secret',duration_ms:5},{type:'api',path:'/api/mailboxes/credentials/reveal',body:'secret'}]};const{api}=load(saved);const report=JSON.parse(api.exportDiagnostics());assert.equal(report.rows.length,1);assert.equal(report.rows[0].path,'/api/posts/:id');assert(!JSON.stringify(report).includes('secret'));assert.equal(load({...saved,expires:10}).api.diagnosticState(),null);});
test('request started before a new diagnostic session cannot enter the new report',()=>{const{api}=load();api.startDiagnostics('relay-on');const task=api.beginApiDiagnostic('/posts');api.startDiagnostics('relay-off');task.finish();assert.equal(api.diagnosticState().rows.length,0);});
test('a failed observer cannot interrupt application work',()=>{const{api}=load();api.subscribeDiagnostics(()=>{throw Error('broken UI');});assert.doesNotThrow(()=>api.startDiagnostics('unknown'));assert.doesNotThrow(()=>api.beginApiDiagnostic('/site-settings').finish());});
