const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function plain(value){return String(value||'').replace(/^\s*(?:>\s*)?(?:\*\*)?提醒[：:]\s*本文最后更新于\s*[\d\s/:年月日-]+[，,]\s*文中所关联的信息可能已发生改变[，,]\s*请知悉[！!。.]?(?:\*\*)?\s*/u,'').replace(/```[\s\S]*?```/g,' ').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/<[^>]*>/g,' ').replace(/[#*_>`~]/g,'').replace(/\s+/g,' ').trim();}
function origin(){const u=new URL(process.env.SITE_URL||'https://mooncci.site');if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('Invalid SITE_URL');return u.origin;}
function imageUrl(value,base=origin()){try{const u=new URL(String(value||'/default-share.png'),base);if(['http:','https:'].includes(u.protocol)&&!u.username&&!u.password)return u.href;}catch{}return base+'/default-share.png';}
const descriptions={'/':'mooncci 的个人技术手记，分享开发实践、文章、近况与作品。','/articles':'阅读前端、后端与技术实践文章。','/archives':'按发布时间浏览 mooncci 的历史文章。','/about':'了解 mooncci 与这个个人技术博客。','/links':'发现值得访问的朋友们的网站。','/projects':'浏览持续构建与维护的作品和实验。','/updates':'查看文章、日常近况与作品版本更新。','/tags':'按标签查找感兴趣的技术文章。','/categories':'按分类浏览 mooncci 的文章。','/rss':'通过 RSS 订阅最新文章和更新。','/series':'按专栏连续阅读相关主题的文章。','/early-access':'了解 PromptDock，并申请参与抢先体验。','/mail-setup':'查看 mooncci 邮箱的 IMAP、SMTP 设置和客户端配置方法。'};
const titles={'/':'首页','/articles':'文章','/archives':'文章归档','/about':'关于我','/links':'友情链接','/projects':'作品','/updates':'近况','/tags':'标签','/categories':'分类','/rss':'RSS 订阅','/series':'文章专栏','/early-access':'PromptDock 抢先体验','/mail-setup':'邮箱客户端配置'};
function baseMeta(path,brand={}){const name=String(brand.site_title||'mooncci');const publicDetail=/^\/(projects|updates|category|tag)\/[^/]+$/.test(path);return {title:`${titles[path]||'页面'} · ${name}`,description:descriptions[path]||'记录文章、日常近况与作品进展。',canonical:origin()+path,siteName:name,image:imageUrl(brand.share_image_url),type:'website',robots:titles[path]||publicDetail?'index, follow':'noindex, follow',jsonLd:null};}
function iso(value){const d=new Date(value);return value&&Number.isFinite(d.getTime())?d.toISOString():undefined;}
function articleMeta(post,brand={}){const m=baseMeta(`/article/${post.id}`,brand);const published=iso(post.published_at||post.created_at),modified=iso(post.updated_at||post.published_at||post.created_at);return {...m,title:`${post.title} · ${m.siteName}`,description:(plain(post.summary)||plain(post.content)).slice(0,160),image:imageUrl(post.cover_image||brand.share_image_url),type:'article',robots:'index, follow',published,modified,jsonLd:{'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,description:(plain(post.summary)||plain(post.content)).slice(0,160),image:[imageUrl(post.cover_image||brand.share_image_url)],datePublished:published,dateModified:modified,author:{'@type':'Person',name:post.author_name||m.siteName},mainEntityOfPage:m.canonical,url:m.canonical}};}
function updateMeta(update,brand={}){const m=baseMeta(`/updates/${update.id}`,brand);const description=plain(update.content).slice(0,160);return {...m,title:`${description.slice(0,48)||'近况'} · ${m.siteName}`,description:description||'mooncci 的近况。',image:imageUrl(update.image_url||brand.share_image_url),robots:'index, follow'};}
function projectMeta(project,brand={}){const m=baseMeta(`/projects/${encodeURIComponent(project.slug)}`,brand);return {...m,title:`${project.name} · ${m.siteName}`,description:plain(project.summary||project.content).slice(0,160),image:imageUrl(project.cover_image||brand.share_image_url),robots:'index, follow'};}
function categoryMeta(category,brand={}){const m=baseMeta(`/category/${encodeURIComponent(category)}`,brand);return {...m,title:`${category} · 分类 · ${m.siteName}`,description:`阅读 mooncci 的「${category}」分类文章。`,robots:'index, follow'};}
function renderHtml(template,meta){
 const clean=template.replace(/<title[^>]*>[\s\S]*?<\/title>/gi,'').replace(/<meta\b(?=[^>]*(?:name=["'](?:description|robots|twitter:[^"']+)["']|property=["'](?:og:[^"']+|article:[^"']+)["']))[^>]*>/gi,'').replace(/<link\b(?=[^>]*rel=["']canonical["'])[^>]*>/gi,'').replace(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi,'');
 const tags=[`<title>${escape(meta.title)}</title>`,`<meta name="description" content="${escape(meta.description)}">`,`<meta name="robots" content="${escape(meta.robots)}">`,`<link rel="canonical" href="${escape(meta.canonical)}">`,...Object.entries({'og:title':meta.title,'og:description':meta.description,'og:url':meta.canonical,'og:image':meta.image,'og:type':meta.type,'og:site_name':meta.siteName,'article:published_time':meta.published,'article:modified_time':meta.modified}).filter(([,v])=>v).map(([k,v])=>`<meta property="${k}" content="${escape(v)}">`)];
 for(const [key,value] of Object.entries({'twitter:card':'summary_large_image','twitter:title':meta.title,'twitter:description':meta.description,'twitter:image':meta.image})) tags.push(`<meta name="${key}" content="${escape(value)}">`);
 if(meta.jsonLd)tags.push(`<script id="article-jsonld" type="application/ld+json">${JSON.stringify(meta.jsonLd).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026')}</script>`);
 return clean.replace('</head>',tags.join('\n')+'\n</head>');
}
function sitemap(rows){return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+rows.map(r=>`<url><loc>${escape(origin()+r.path)}</loc>${iso(r.updated_at)?`<lastmod>${iso(r.updated_at)}</lastmod>`:''}</url>`).join('')+'</urlset>';}
module.exports={escape,plain,origin,baseMeta,articleMeta,updateMeta,projectMeta,categoryMeta,renderHtml,sitemap,titles};
