const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function plain(value){return String(value||'').replace(/```[\s\S]*?```/g,' ').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/<[^>]*>/g,' ').replace(/[#*_>`~]/g,'').replace(/\s+/g,' ').trim();}
function origin(){const u=new URL(process.env.SITE_URL||'https://mooncci.site');if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('Invalid SITE_URL');return u.origin;}
function imageUrl(value,base=origin()){try{const u=new URL(String(value||'/default-share.png'),base);if(['http:','https:'].includes(u.protocol)&&!u.username&&!u.password)return u.href;}catch{}return base+'/default-share.png';}
const titles={'/':'首页','/articles':'文章','/archives':'文章归档','/about':'关于我','/links':'友情链接','/projects':'作品','/updates':'近况','/tags':'标签','/categories':'分类','/rss':'RSS 订阅'};
function baseMeta(path,brand={}){const name=String(brand.site_title||'mooncci');const publicDetail=/^\/(projects|updates|category|tag)\/[^/]+$/.test(path);return {title:`${titles[path]||'页面'} · ${name}`,description:'记录文章、日常近况与作品进展。',canonical:origin()+path,siteName:name,image:imageUrl(brand.share_image_url),type:'website',robots:titles[path]||publicDetail?'index, follow':'noindex, follow',jsonLd:null};}
function iso(value){const d=new Date(value);return value&&Number.isFinite(d.getTime())?d.toISOString():undefined;}
function articleMeta(post,brand={}){const m=baseMeta(`/article/${post.id}`,brand);const published=iso(post.published_at||post.created_at),modified=iso(post.updated_at||post.published_at||post.created_at);return {...m,title:`${post.title} · ${m.siteName}`,description:plain(post.summary||post.content).slice(0,160),image:imageUrl(post.cover_image||brand.share_image_url),type:'article',robots:'index, follow',published,modified,jsonLd:{'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,description:plain(post.summary||post.content).slice(0,160),image:[imageUrl(post.cover_image||brand.share_image_url)],datePublished:published,dateModified:modified,author:{'@type':'Person',name:post.author_name||m.siteName},mainEntityOfPage:m.canonical,url:m.canonical}};}
function renderHtml(template,meta){
 const clean=template.replace(/<title[^>]*>[\s\S]*?<\/title>/gi,'').replace(/<meta\b(?=[^>]*(?:name=["'](?:description|robots)["']|property=["'](?:og:[^"']+|article:[^"']+)["']))[^>]*>/gi,'').replace(/<link\b(?=[^>]*rel=["']canonical["'])[^>]*>/gi,'').replace(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi,'');
 const tags=[`<title>${escape(meta.title)}</title>`,`<meta name="description" content="${escape(meta.description)}">`,`<meta name="robots" content="${escape(meta.robots)}">`,`<link rel="canonical" href="${escape(meta.canonical)}">`,...Object.entries({'og:title':meta.title,'og:description':meta.description,'og:url':meta.canonical,'og:image':meta.image,'og:type':meta.type,'og:site_name':meta.siteName,'article:published_time':meta.published,'article:modified_time':meta.modified}).filter(([,v])=>v).map(([k,v])=>`<meta property="${k}" content="${escape(v)}">`)];
 if(meta.jsonLd)tags.push(`<script id="article-jsonld" type="application/ld+json">${JSON.stringify(meta.jsonLd).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026')}</script>`);
 return clean.replace('</head>',tags.join('\n')+'\n</head>');
}
function sitemap(rows){return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+rows.map(r=>`<url><loc>${escape(origin()+r.path)}</loc>${iso(r.updated_at)?`<lastmod>${iso(r.updated_at)}</lastmod>`:''}</url>`).join('')+'</urlset>';}
module.exports={escape,plain,origin,baseMeta,articleMeta,renderHtml,sitemap,titles};
