CREATE TABLE IF NOT EXISTS analytics_meta (
 id TINYINT NOT NULL PRIMARY KEY, started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO analytics_meta(id) VALUES (1);
CREATE TABLE IF NOT EXISTS analytics_visits (
 day DATE NOT NULL,
 visitor CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 page_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 path VARCHAR(512) NOT NULL,
 views INT UNSIGNED NOT NULL DEFAULT 0,
 last_seen BIGINT NOT NULL DEFAULT 0,
 member TINYINT NOT NULL DEFAULT 0,
 device VARCHAR(16) NOT NULL,
 source VARCHAR(253) NOT NULL,
 PRIMARY KEY(day,visitor,page_hash), INDEX visits_day_seen(day,last_seen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS analytics_daily (
 day DATE NOT NULL, page_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 path VARCHAR(512) NOT NULL, views BIGINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY(day,page_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS analytics_article_totals (
 post_id INT NOT NULL PRIMARY KEY, views BIGINT UNSIGNED NOT NULL DEFAULT 0,
 CONSTRAINT fk_analytics_post FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
