CREATE TABLE IF NOT EXISTS article_workflows (
 draft_id CHAR(36) NOT NULL PRIMARY KEY,
 state VARCHAR(20) NOT NULL DEFAULT 'draft',
 draft_version INT NOT NULL,
 snapshot JSON NOT NULL,
 reviewer_id INT NULL,
 reason VARCHAR(1000) NOT NULL DEFAULT '',
 scheduled_at BIGINT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 KEY idx_workflow_due (state,scheduled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS article_series (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(191) NOT NULL UNIQUE,
 title VARCHAR(255) NOT NULL,
 description TEXT NOT NULL,
 cover_image VARCHAR(500) NOT NULL DEFAULT '',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS article_series_posts (
 post_id INT NOT NULL PRIMARY KEY,
 series_id INT NOT NULL,
 position INT NOT NULL DEFAULT 0,
 KEY idx_series_order (series_id,position,post_id),
 FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
 FOREIGN KEY (series_id) REFERENCES article_series(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
