const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
test('analytics migration, deduplication, permissions and public-only counters',{skip:process.env.ANALYTICS_INTEGRATION!=='true'},async t=>{
 const name=`mooncci_qa_analytics_${process.pid}`;
 Object.assign(process.env,{DB_HOST:'127.0.0.1',DB_PORT:process.env.TEST_DB_PORT||'33079',DB_USER:'root',DB_PASSWORD:'',DB_NAME:name,JWT_SECRET:'analytics-test-secret-only-more-than-32-chars',SITE_URL:'https://mooncci.site',CSRF_TRUSTED_ORIGINS:'https://mooncci.site'});
 const setup=await require('mysql2/promise').createConnection({host:'127.0.0.1',port:Number(process.env.DB_PORT),user:'root',multipleStatements:true});
 await setup.query(`CREATE DATABASE ${name} CHARACTER SET utf8mb4`);await setup.query(`USE ${name}`);
 await setup.query(fs.readFileSync(path.join(__dirname,'../database/schema.sql'),'utf8'));
 await setup.query(fs.readFileSync(path.join(__dirname,'../database/migrations/202609090002_auth_revocation.sql'),'utf8'));
 await setup.query('DROP TABLE analytics_article_totals,analytics_visits,analytics_daily,analytics_meta');
 const sql=fs.readFileSync(path.join(__dirname,'../database/migrations/202609140001_analytics.sql'),'utf8');await setup.query(sql);await setup.query(sql);
 const db=require('../src/db'),jwt=require('jsonwebtoken');
 const [owner]=await db.query('INSERT INTO users(username,email,password_hash,role) VALUES ("owner","owner@example.test","unused","owner")');
 const [member]=await db.query('INSERT INTO users(username,email,password_hash,role) VALUES ("member","member@example.test","unused","user")');
 const [post]=await db.query('INSERT INTO posts(title,slug,content,status,author_id) VALUES ("Public","public","body","published",?)',[owner.insertId]);
 const [draft]=await db.query('INSERT INTO posts(title,slug,content,status,author_id) VALUES ("Private","private","secret","draft",?)',[owner.insertId]);
 const server=require('../src/index').listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(async()=>{await new Promise(r=>server.close(r));await db.end();await require('../src/platformDb').end();await setup.query(`DROP DATABASE ${name}`);await setup.end();});
 const auth=id=>`mooncci_token=${jwt.sign({id,sessionStartedAt:Date.now()},process.env.JWT_SECRET)}`;
 const cookie='mooncci_visit='+ 'a'.repeat(32);
 const request=(url,method='GET',body,c=cookie,extra={})=>fetch(`http://127.0.0.1:${server.address().port}/api${url}`,{method,headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest',Origin:'https://mooncci.site',Cookie:c,...extra},...(body?{body:JSON.stringify(body)}:{})});
 const data={path:`/article/${post.insertId}`,referrer:'https://example.test/private?token=secret',device:'mobile'};
 const responses=await Promise.all(Array.from({length:4},()=>request('/analytics/view','POST',data)));assert.ok(responses.every(x=>x.status===200));
 assert.equal((await (await request(`/analytics/article/${post.insertId}`)).json()).views,1);
 assert.equal((await request(`/analytics/article/${draft.insertId}`)).status,404);
 for(const route of [`/article/${draft.insertId}`,'/admin','/account/settings','/search?token=secret','/article/999999'])assert.equal((await request('/analytics/view','POST',{path:route})).status,400);
 assert.equal((await request('/admin/analytics')).status,401);assert.equal((await request('/admin/analytics','GET',null,auth(member.insertId))).status,403);
 assert.equal((await (await request('/analytics/view','POST',data,auth(owner.insertId))).json()).counted,false);
 assert.equal((await (await request('/analytics/view','POST',data,'',{'DNT':'1'})).json()).counted,false);
 assert.equal((await (await request('/analytics/view','POST',data,'',{'User-Agent':'Googlebot'})).json()).counted,false);
 await db.query('UPDATE analytics_visits SET last_seen=last_seen-31000');
 assert.equal((await (await request('/analytics/view','POST',data)).json()).views,2);
 const r=await request('/admin/analytics?days=7','GET',null,auth(owner.insertId));assert.equal(r.status,200);const stats=await r.json();
 assert.equal(Number(stats.summary.views),2);assert.equal(Number(stats.summary.visitors),1);assert.equal(stats.trend.length,7);
 assert.equal(stats.sources[0].label,'example.test');assert.ok(!JSON.stringify(stats).includes('token=secret'));
 assert.equal((await request('/admin/analytics?days=999','GET',null,auth(owner.insertId))).status,400);
 const [[record]]=await db.query('SELECT visitor,source FROM analytics_visits');assert.notEqual(record.visitor,'a'.repeat(32));
 await db.query('UPDATE posts SET status="draft" WHERE id=?',[post.insertId]);assert.equal((await request(`/analytics/article/${post.insertId}`)).status,404);
});
