const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
test('article drafts isolate public content, enforce versions and publish idempotently',{skip:process.env.DRAFT_INTEGRATION!=='true'},async t=>{
 const name=`mooncci_qa_drafts_${process.pid}`;
 Object.assign(process.env,{DB_HOST:'127.0.0.1',DB_PORT:process.env.TEST_DB_PORT||'33079',DB_USER:'root',DB_PASSWORD:'',DB_NAME:name,JWT_SECRET:'draft-test-secret-only-more-than-32-chars',SITE_URL:'https://mooncci.site',CSRF_TRUSTED_ORIGINS:'https://mooncci.site'});
 const setup=await require('mysql2/promise').createConnection({host:'127.0.0.1',port:Number(process.env.DB_PORT),user:'root',multipleStatements:true});
 await setup.query(`CREATE DATABASE ${name} CHARACTER SET utf8mb4`);await setup.query(`USE ${name}`);await setup.query(fs.readFileSync(path.join(__dirname,'../database/schema.sql'),'utf8'));await setup.query(fs.readFileSync(path.join(__dirname,'../database/migrations/202609090002_auth_revocation.sql'),'utf8'));
 const db=require('../src/db'),jwt=require('jsonwebtoken');const [owner]=await db.query('INSERT INTO users(username,email,password_hash,role) VALUES ("writer","writer@example.test","unused","editor")');const [other]=await db.query('INSERT INTO users(username,email,password_hash,role) VALUES ("other","other@example.test","unused","editor")');
 await db.query('DROP TABLE article_drafts');await db.query('ALTER TABLE posts DROP COLUMN version');
 await db.query('INSERT INTO posts(title,slug,content,status,author_id) VALUES ("Existing","existing","Keep original content","published",?)',[owner.insertId]);
 await setup.query(fs.readFileSync(path.join(__dirname,'../database/migrations/202609110001_article_drafts.sql'),'utf8'));
 const [[legacy]]=await db.query('SELECT content,version FROM posts WHERE slug="existing"');assert.equal(legacy.content,'Keep original content');assert.equal(legacy.version,1);
 const token=id=>`mooncci_token=${jwt.sign({id,sessionStartedAt:Date.now()},process.env.JWT_SECRET)}`;const cookie=token(owner.insertId);
 const server=require('../src/index').listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));await db.end();await require('../src/platformDb').end();await setup.query(`DROP DATABASE ${name}`);await setup.end();});
 const req=(url,method='GET',body,auth=cookie)=>fetch(`http://127.0.0.1:${server.address().port}/api${url}`,{method,headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest',Origin:'https://mooncci.site',Cookie:auth},...(body?{body:JSON.stringify(body)}:{})});
 const id=crypto.randomUUID();let r=await req('/article-drafts','POST',{id,payload:{}});assert.equal(r.status,200);let d=await r.json();assert.equal(d.version,1);
 assert.equal((await req('/article-drafts','POST',{id,payload:{title:'ignored'}})).status,200);
 assert.equal((await req(`/article-drafts/${id}`,'GET',null,'')).status,401);
 assert.equal((await req(`/article-drafts/${id}`,'GET',null,token(other.insertId))).status,404);
 assert.equal((await req(`/article-drafts/${id}/publish`,'POST',{version:1})).status,400);
 r=await req(`/article-drafts/${id}`,'PUT',{version:1,payload:{title:'Draft title',content:'First public body',slug:'draft-test'}});assert.equal(r.status,200);d=await r.json();
 assert.equal((await req(`/article-drafts/${id}`,'PUT',{version:1,payload:{title:'stale'}})).status,409);
 r=await req(`/article-drafts/${id}/publish`,'POST',{version:d.version});assert.equal(r.status,200);d=await r.json();assert.ok(d.post_id);
 const published=await (await req(`/posts/${d.post_id}`,'GET',null,'')).json();assert.equal(published.content,'First public body');
 const replay=await (await req(`/article-drafts/${id}/publish`,'POST',{version:d.version})).json();assert.equal(replay.post_id,d.post_id);assert.equal(replay.replayed,true);
 d=await (await req(`/article-drafts/${id}`,'PUT',{version:d.version,payload:{...d.payload,content:'Unpublished revision'}})).json();assert.equal((await (await req(`/posts/${d.post_id}`,'GET',null,'')).json()).content,'First public body');
 d=await (await req(`/article-drafts/${id}/publish`,'POST',{version:d.version})).json();const updated=await(await req(`/posts/${d.post_id}`)).json();assert.equal(updated.content,'Unpublished revision');assert.equal(updated.published_at,published.published_at);
 d=await(await req(`/article-drafts/${id}/withdraw`,'POST',{version:d.version})).json();assert.equal((await req(`/posts/${d.post_id}`,'GET',null,'')).status,404);
 await db.query('UPDATE posts SET version=version+1 WHERE id=?',[d.post_id]);assert.equal((await req(`/article-drafts/${id}/publish`,'POST',{version:d.version})).status,409);
 assert.equal((await req(`/article-drafts/${id}`,'DELETE',{version:d.version})).status,200);assert.equal((await req(`/posts/${d.post_id}`)).status,200);
});
