const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
test('guidance real MySQL: reset task continuity, automatic series links and guarded mail retry',{skip:process.env.GUIDANCE_INTEGRATION!=='true'},async t=>{
const name='mooncci_qa_guidance_'+process.pid;Object.assign(process.env,{DB_HOST:'127.0.0.1',DB_PORT:process.env.TEST_DB_PORT||'33079',DB_USER:'root',DB_PASSWORD:'',DB_NAME:name,JWT_SECRET:'guidance-test-only',ACCOUNT_OPERATIONS_ENABLED:'true',ENGAGEMENT_ENABLED:'true',PUBLISHING_ENABLED:'true',MAIL_ENABLED:'false'});
const c=await require('mysql2/promise').createConnection({host:'127.0.0.1',port:Number(process.env.TEST_DB_PORT||33079),user:'root',multipleStatements:true});let server,db;
try{await c.query('CREATE DATABASE '+name+' CHARACTER SET utf8mb4');await c.query('USE '+name);await c.query(fs.readFileSync(path.join(__dirname,'../database/schema.sql'),'utf8'));await c.query(fs.readFileSync(path.join(__dirname,'../database/migrations/202609090002_auth_revocation.sql'),'utf8'));
const [admin]=await c.query("INSERT INTO users(username,email,password_hash,role) VALUES ('admin','admin@example.test','unused','admin')"),[reader]=await c.query("INSERT INTO users(username,email,password_hash,role) VALUES ('reader','reader@example.test','unused','user')");
const mailer=require('../src/lib/mailer'),mails=[];let configured=true;t.mock.method(mailer,'sendMail',async value=>{mails.push(value);return {sent:true};});t.mock.method(mailer,'getMailConfig',async()=>({enabled:configured?'true':'false',smtp_host:'fixture',smtp_user:'fixture',smtp_pass:'fixture',site_url:'https://mooncci.site'}));
const app=require('express')();app.use(require('express').json());app.use('/api/auth',require('../src/routes/auth-cookie'));app.use('/api/series',require('../src/routes/series'));app.use('/api/admin/operations',require('../src/routes/operations'));app.use((e,req,res,next)=>{console.error(e);res.status(500).json({message:e.message});});db=require('../src/db');
server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const jwt=require('jsonwebtoken'),token=id=>jwt.sign({id,sessionStartedAt:Date.now()},process.env.JWT_SECRET),ad=token(admin.insertId),rd=token(reader.insertId);
const call=(url,method='GET',body,who=ad)=>fetch('http://127.0.0.1:'+server.address().port+'/api'+url,{method,headers:{'Content-Type':'application/json',Cookie:'mooncci_token='+who},body:body?JSON.stringify(body):undefined});
let r=await call('/auth/forgot-password','POST',{email:'reader@example.test',return_to:'/account/submissions?token=do-not-copy'});assert.equal(r.status,200);const resetUrl=new URL(mails.at(-1).text.match(/https:\/\/[^\s]+/)[0]);assert.equal(resetUrl.searchParams.get('redirect'),'/account/submissions');assert.equal(resetUrl.searchParams.get('token'),null);const resetToken=new URLSearchParams(resetUrl.hash.slice(1)).get('token');assert.equal(resetToken.length,64);r=await call('/auth/reset-password','POST',{token:resetToken,password:'NewPassword2026!'});assert.equal(r.status,200);assert.equal((await call('/auth/reset-password','POST',{token:resetToken,password:'NewPassword2026!'})).status,400);
const fresh=token(reader.insertId);const series=await(await call('/series','POST',{title:'中文专栏',description:'简介'})).json();assert.match(series.slug,/^series-[a-f0-9]{12}$/);const another=await(await call('/series','POST',{title:'中文专栏'})).json();assert.notEqual(series.slug,another.slug);assert.equal((await call('/series','POST',{title:'冲突',slug:series.slug})).status,409);assert.equal((await call('/series','POST',{title:'无权创建'},fresh)).status,403);
const [post]=await c.query("INSERT INTO posts(title,slug,content,status,author_id) VALUES ('Article','retry-test','body','published',?)",[admin.insertId]);const [comment]=await c.query("INSERT INTO comments(post_id,user_id,content,status) VALUES (?,?,'reply','visible')",[post.insertId,admin.insertId]);const [notification]=await c.query("INSERT INTO account_notifications(user_id,event_key,kind,post_id,comment_id) VALUES (?,'retry','reply',?,?)",[reader.insertId,post.insertId,comment.insertId]);const id=notification.insertId;
const engagement=require('../src/services/engagement');await engagement.preferences(c,reader.insertId);await c.query('UPDATE engagement_preferences SET reply_email=1,verified_email=? WHERE user_id=?',['reader@example.test',reader.insertId]);await c.query("INSERT INTO notification_mail_jobs(notification_id,state,attempts,last_error) VALUES (?,'failed',5,'internal-detail-must-not-leak')",[id]);
assert.equal((await call('/admin/operations/mail-failures','GET',null,fresh)).status,403);r=await call('/admin/operations/mail-failures');assert.match(r.headers.get('cache-control'),/no-store/);const list=await r.json();assert.equal(list.items.length,1);assert.ok(!JSON.stringify(list).includes('internal-detail'));
const retry=()=>call('/admin/operations/mail-failures/'+id+'/retry','POST');configured=false;assert.equal((await retry()).status,409);configured=true;
await c.query('UPDATE engagement_preferences SET reply_email=0 WHERE user_id=?',[reader.insertId]);assert.equal((await retry()).status,409);await c.query('UPDATE engagement_preferences SET reply_email=1 WHERE user_id=?',[reader.insertId]);
await c.query("UPDATE comments SET status='hidden' WHERE id=?",[comment.insertId]);assert.equal((await retry()).status,409);await c.query("UPDATE comments SET status='visible' WHERE id=?",[comment.insertId]);
const races=await Promise.all([retry(),retry()]);assert.deepEqual(races.map(x=>x.status).sort(),[200,409]);const [[job]]=await c.query('SELECT * FROM notification_mail_jobs WHERE notification_id=?',[id]);assert.equal(job.state,'pending');assert.equal(job.attempts,0);
await c.query('UPDATE engagement_preferences SET reply_email=0 WHERE user_id=?',[reader.insertId]);let sent=0;await engagement.runMail(async()=>{sent++;return {sent:true};});assert.equal(sent,0);assert.equal((await c.query('SELECT state FROM notification_mail_jobs WHERE notification_id=?',[id]))[0][0].state,'skipped');
console.log('PASS: mail links preserve task without query credentials; reset one-use; auto series slug uniqueness; retry admin-only/no-store/config/preferences/visibility/concurrency; worker rechecks opt-out. No external delivery.');
}finally{if(server)await new Promise(r=>server.close(r));if(db)await db.end();await c.query('DROP DATABASE IF EXISTS '+name);await c.end();}
});
