const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

test('social login, owner settings, mandatory email, binding, revocation and replay protection', { skip: process.env.SOCIAL_INTEGRATION !== 'true' }, async t => {
  // Dedicated disposable local schema; never load production connection details.
  Object.assign(process.env, { DB_HOST: '127.0.0.1', DB_PORT: process.env.TEST_DB_PORT || '33079', DB_USER: 'root', DB_PASSWORD: '', DB_NAME: 'mooncci_qa_social_login',
    JWT_SECRET: 'social-integration-fixture-secret-32-characters', SITE_URL: 'https://mooncci.site', COOKIE_SECURE: 'true', CSRF_TRUSTED_ORIGINS: 'https://mooncci.site' });
  const mysql = require('mysql2/promise');
  const setup = await mysql.createConnection({ host: '127.0.0.1', port: Number(process.env.DB_PORT), user: 'root', password: '', multipleStatements: true });
  await setup.query('CREATE DATABASE IF NOT EXISTS mooncci_qa_social_login CHARACTER SET utf8mb4');
  await setup.query('USE mooncci_qa_social_login');
  await setup.query(`CREATE TABLE IF NOT EXISTS users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) UNIQUE, email VARCHAR(120) UNIQUE, password_hash VARCHAR(255), google_sub VARCHAR(255) UNIQUE, role VARCHAR(16), status VARCHAR(16), can_comment INT DEFAULT 1, login_attempts INT DEFAULT 0, locked_until DATETIME NULL)`);
  for (const file of ['202609090002_auth_revocation.sql', '202609100001_social_login.sql']) await setup.query(fs.readFileSync(path.join(__dirname, '../database/migrations', file), 'utf8'));
  await setup.query('DELETE FROM oauth_identities; DELETE FROM oauth_providers; DELETE FROM oauth_states; DELETE FROM oauth_registrations; DELETE FROM auth_revocations; DELETE FROM auth_invalidations; DELETE FROM users');
  await setup.end();
  const db = require('../src/db');
  const adapters = require('../src/lib/socialProviders');
  const google = require('../src/lib/googleIdentity');
  const mailer = require('../src/lib/mailer');
  let identity = { subject: 'subject1', name: 'Fixture', emailVerified: false };
  let exchangeHook = null;
  let exchanges = 0;
  t.mock.method(adapters, 'exchange', async () => { exchanges++; if (exchangeHook) await exchangeHook(); return identity; });
  let googlePayload = { sub: 'legacy-google', email: 'legacy@gmail.com', email_verified: true, name: 'Legacy' };
  t.mock.method(google, 'verifyGoogleCredential', async (_token, audience) => { assert.ok(audience.endsWith('.apps.googleusercontent.com')); return googlePayload; });
  let mailedCode = '';
  t.mock.method(mailer, 'sendMail', async ({ text }) => { mailedCode = text.match(/\b\d{6}\b/)[0]; return { sent: true }; });
  const jwt = require('jsonwebtoken');
  const app = require('../src/index');
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(async () => { await new Promise(resolve => server.close(resolve)); await db.end(); await require('../src/platformDb').end(); });
  const base = `http://127.0.0.1:${server.address().port}/api/auth`;
  let sequence = 0;
  const req = (url, method = 'GET', body, cookie = '', headers = {}) => fetch(base + url, { method, redirect: 'manual', headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest', Origin: 'https://mooncci.site', 'X-Forwarded-For': `192.0.2.${++sequence % 250 + 1}`, Cookie: cookie, ...headers }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const makeUser = async (role, sub = null) => { const [r] = await db.query("INSERT INTO users (username,email,password_hash,role,status,google_sub) VALUES (?,?,? ,?,'active',?)", [`${role}-${sequence}`, `${role}-${Date.now()}@example.test`, 'fixture', role, sub]); return r.insertId; };
  const token = id => `mooncci_token=${jwt.sign({ id, sessionStartedAt: Date.now(), jti: String(Math.random()) }, process.env.JWT_SECRET, { expiresIn: '1h' })}`;
  const owner = token(await makeUser('owner')), memberId = await makeUser('user'), member = token(memberId);
  const cookieOf = (r, name) => r.headers.getSetCookie().find(c => c.startsWith(`${name}=`))?.split(';')[0] || '';
  const initial = await (await req('/providers')).json();
  assert.deepEqual(initial.providers.map(p => p.provider), ['google']);
  assert.equal((await req('/providers/manage')).status, 401);
  assert.equal((await req('/providers/manage', 'GET', null, member)).status, 403);
  assert.equal((await req('/providers/manage/qq', 'PUT', {}, owner, { 'X-Requested-With': '' })).status, 403);
  assert.equal((await req('/providers/manage/qq', 'PUT', {}, owner, { Origin: 'https://evil.test' })).status, 403);
  const save = (provider, data) => req(`/providers/manage/${provider}`, 'PUT', data, owner);
  assert.equal((await save('qq', { enabled: true, client_id: '123', version: 0 })).status, 400);
  assert.equal((await save('__proto__', { enabled: false, client_id: '', version: 0 })).status, 404);
  for (const provider of ['qq', 'github', 'wechat', 'gitee']) {
    const r = await save(provider, { enabled: true, client_id: '123', client_secret: 'fixture-secret', version: 0 });
    assert.equal(r.status, 200); const body = await r.text(); assert.ok(!body.includes('fixture-secret')); assert.ok(!body.includes('secret_cipher'));
  }
  const [[stored]] = await db.query("SELECT * FROM oauth_providers WHERE provider='qq'"); assert.ok(!stored.secret_cipher.includes('fixture-secret'));
  assert.equal((await save('qq', { enabled: true, client_id: '123', version: 0 })).status, 409);
  assert.equal((await save('qq', { enabled: true, client_id: '123', client_secret: '', version: 1 })).status, 200);
  const [[preserved]] = await db.query("SELECT * FROM oauth_providers WHERE provider='qq'"); assert.equal(preserved.secret_cipher, stored.secret_cipher);
  assert.equal((await save('qq', { enabled: true, client_id: 'changed', version: 2 })).status, 400);
  async function start(provider, cookie = '', mode = 'login') {
    const r = await req(`/${provider}/start`, 'POST', { mode, return_to: '//evil.test' }, cookie);
    assert.equal(r.status, 200);
    const url = new URL((await r.json()).url);
    return { path: `/${provider}/callback?code=code&state=${url.searchParams.get('state')}`, cookie: [cookie, cookieOf(r, `mooncci_oauth_${provider}`)].filter(Boolean).join('; ') };
  }
  let flow = await start('qq');
  let r = await req(flow.path, 'GET', null, ''); assert.match(r.headers.get('location'), /failed/); assert.equal(exchanges, 0);
  r = await req(flow.path, 'GET', null, flow.cookie); assert.equal(r.headers.get('location'), '/complete-registration'); assert.equal(cookieOf(r, 'mooncci_token'), '');
  const pending = cookieOf(r, 'mooncci_registration'); assert.ok(pending);
  assert.equal((await req('/me', 'GET', null, pending)).status, 401, 'pending registration is not an authenticated user');
  assert.match((await req(flow.path, 'GET', null, flow.cookie)).headers.get('location'), /failed/); assert.equal(exchanges, 1, 'state is single-use');
  assert.equal((await req('/registration/email', 'POST', { email: 'a,b@example.test' }, pending)).status, 400);
  assert.equal((await req('/registration/email', 'POST', { email: 'new@example.test' }, pending)).status, 200);
  assert.equal((await req('/registration/email', 'POST', { email: 'new@example.test' }, pending)).status, 429);
  assert.equal((await req('/registration/complete', 'POST', { email: 'new@example.test', code: '000000' }, pending)).status, 400);
  r = await req('/registration/complete', 'POST', { email: 'new@example.test', code: mailedCode }, pending); assert.equal(r.status, 200);
  const auth = cookieOf(r, 'mooncci_token'); assert.ok(auth);
  const current = await (await req('/me', 'GET', null, auth)).json(); assert.equal(current.user.email, 'new@example.test'); assert.equal(current.user.role, 'user');
  assert.equal((await req('/registration/complete', 'POST', { email: 'new@example.test', code: mailedCode }, pending)).status, 400);
  await req('/logout', 'POST', {}, auth);
  assert.equal((await req('/me', 'GET', null, auth)).status, 401, 'new social session participates in persistent logout revocation');
  flow = await start('qq'); r = await req(flow.path, 'GET', null, flow.cookie); assert.equal(r.headers.get('location'), '/'); assert.ok(cookieOf(r, 'mooncci_token'));
  flow = await start('qq', member, 'bind'); r = await req(flow.path, 'GET', null, flow.cookie); assert.match(r.headers.get('location'), /failed/, 'cannot steal another user identity');
  identity = { subject: 'new-gitee-binding', name: 'Member', emailVerified: false };
  flow = await start('gitee', member, 'bind'); r = await req(flow.path, 'GET', null, flow.cookie); assert.equal(r.headers.get('location'), '/account/settings?oauth=bound');
  identity = { subject: 'wechat-after-logout', name: 'Member' };
  flow = await start('wechat', member, 'bind'); await req('/logout', 'POST', {}, member);
  r = await req(flow.path, 'GET', null, flow.cookie); assert.match(r.headers.get('location'), /failed/);
  identity = { subject: 'github1', name: 'GitHub', email: 'verified@example.test', emailVerified: true };
  flow = await start('github'); r = await req(flow.path, 'GET', null, flow.cookie); assert.ok(cookieOf(r, 'mooncci_token'));
  const githubUser = await (await req('/me', 'GET', null, cookieOf(r, 'mooncci_token'))).json();
  await db.query("UPDATE users SET status='disabled' WHERE id=?", [githubUser.user.id]);
  flow = await start('github'); r = await req(flow.path, 'GET', null, flow.cookie); assert.match(r.headers.get('location'), /failed/); assert.equal(cookieOf(r, 'mooncci_token'), '');
  identity = { subject: 'different-github', name: 'GitHub', email: 'verified@example.test', emailVerified: true };
  flow = await start('github'); r = await req(flow.path, 'GET', null, flow.cookie); assert.match(r.headers.get('location'), /email_exists/);
  identity = { subject: 'disabled-during-exchange', name: 'QQ' };
  exchangeHook = () => db.query("UPDATE oauth_providers SET enabled=0,version=version+1 WHERE provider='qq'");
  flow = await start('qq'); r = await req(flow.path, 'GET', null, flow.cookie); assert.match(r.headers.get('location'), /failed/); exchangeHook = null;
  assert.equal((await req('/qq/start', 'POST', {})).status, 403);
  const legacyId = await makeUser('user', 'legacy-google');
  r = await req('/google', 'POST', { credential: 'fixture' }); assert.equal(r.status, 200); assert.equal((await r.json()).user.id, legacyId, 'existing google_sub remains linked');
  googlePayload = { ...googlePayload, sub: 'external-email-google', email: 'untrusted@example.test' };
  r = await req('/google', 'POST', { credential: 'fixture' }); assert.equal((await r.json()).registration_required, true); assert.equal(cookieOf(r, 'mooncci_token'), '');
  identity = { subject: 'email-attempt-fixture', name: 'Needs email' };
  flow = await start('gitee'); r = await req(flow.path, 'GET', null, flow.cookie);
  const attemptCookie = cookieOf(r, 'mooncci_registration');
  assert.equal((await req('/registration/email', 'POST', { email: 'attempts@example.test' }, attemptCookie)).status, 200);
  for (let i = 0; i < 5; i++) assert.equal((await req('/registration/complete', 'POST', { email: 'attempts@example.test', code: '000000' }, attemptCookie)).status, 400);
  assert.equal((await req('/registration/complete', 'POST', { email: 'attempts@example.test', code: mailedCode }, attemptCookie)).status, 400, 'correct code cannot bypass exhausted attempts');
  await db.query('UPDATE oauth_registrations SET expires_at=0');
  assert.equal((await req('/registration', 'GET', null, attemptCookie)).status, 401);
  const googleConfig = (await (await req('/providers/manage', 'GET', null, owner)).json()).providers.find(p => p.provider === 'google');
  assert.equal(googleConfig.callback_url, 'https://mooncci.site/api/auth/google/callback');
  async function startGoogle(cookie = '', mode = 'login') {
    const response = await req('/google/start', 'POST', { mode }, cookie);
    assert.equal(response.status, 200);
    const url = new URL((await response.json()).url);
    assert.equal(url.origin, 'https://accounts.google.com');
    assert.equal(url.searchParams.get('response_type'), 'id_token');
    assert.equal(url.searchParams.get('response_mode'), 'fragment');
    assert.equal(url.searchParams.get('redirect_uri'), googleConfig.callback_url);
    assert.equal(url.searchParams.get('client_secret'), null);
    return { body: { state: url.searchParams.get('state'), credential: 'fixture' }, nonce: url.searchParams.get('nonce'), cookie: [cookie, cookieOf(response, 'mooncci_oauth_google')].filter(Boolean).join('; ') };
  }
  let g = await startGoogle();
  googlePayload = { sub: 'legacy-google', email: 'legacy@gmail.com', email_verified: true, name: 'Legacy', nonce: g.nonce };
  assert.match((await (await req('/google/callback', 'POST', g.body)).json()).redirect, /failed/);
  googlePayload.nonce = 'wrong-nonce';
  assert.match((await (await req('/google/callback', 'POST', g.body, g.cookie)).json()).redirect, /failed/);
  googlePayload.nonce = g.nonce;
  assert.match((await (await req('/google/callback', 'POST', g.body, g.cookie)).json()).redirect, /failed/, 'nonce failure still consumes state');
  g = await startGoogle(); googlePayload.nonce = g.nonce;
  r = await req('/google/callback', 'POST', g.body, g.cookie);
  assert.equal((await r.json()).redirect, '/');
  assert.equal((await (await req('/me', 'GET', null, cookieOf(r, 'mooncci_token'))).json()).user.id, legacyId);
  assert.match((await (await req('/google/callback', 'POST', g.body, g.cookie)).json()).redirect, /failed/, 'redirect credentials cannot replay state');
  g = await startGoogle(); googlePayload = { ...googlePayload, nonce: g.nonce, sub: 'redirect-untrusted', email: 'redirect@example.test' };
  r = await req('/google/callback', 'POST', g.body, g.cookie);
  assert.equal((await r.json()).redirect, '/complete-registration');
  assert.equal(cookieOf(r, 'mooncci_token'), '');
  const bindingUser = token(await makeUser('user', 'already-bound-google'));
  g = await startGoogle(bindingUser, 'bind'); googlePayload = { ...googlePayload, nonce: g.nonce, sub: 'different-google' };
  assert.match((await (await req('/google/callback', 'POST', g.body, g.cookie)).json()).redirect, /failed/, 'cannot replace an existing Google binding');
  const callback = await req('/google/callback');
  assert.match(callback.headers.get('content-security-policy'), /default-src 'none'/);
  assert.match(callback.headers.get('cache-control'), /no-store/);
  const html = await callback.text();
  const script = html.match(/<script nonce="[^"]+">([\s\S]*?)<\/script>/)[1];
  const vm = require('node:vm');
  let erased = false, posted = false, redirect;
  const context = { URLSearchParams, location: { hash: '#id_token=fixture&state=' + 'a'.repeat(64), pathname: '/api/auth/google/callback', replace: value => { redirect = value; } }, history: { replaceState: () => { erased = true; } }, document: { getElementById: () => ({}) }, fetch: async (url, options) => {
    assert.ok(erased, 'remove sensitive fragment before requests');
    assert.equal(url, '/api/auth/google/callback');
    assert.equal(JSON.parse(options.body).credential, 'fixture');
    posted = true; return { ok: true, json: async () => ({ redirect: '/' }) };
  } };
  vm.runInNewContext(script, context);
  await new Promise(resolve => setImmediate(resolve));
  assert.ok(posted); assert.equal(redirect, '/');
  g = await startGoogle(); googlePayload.nonce = g.nonce;
  assert.equal((await save('google', { enabled: false, client_id: googleConfig.client_id, version: googleConfig.version })).status, 200);
  assert.equal((await req('/google', 'POST', { credential: 'fixture' })).status, 403);
  assert.equal((await req('/google/start', 'POST', {})).status, 403);
  assert.match((await (await req('/google/callback', 'POST', g.body, g.cookie)).json()).redirect, /failed/, 'disabled provider rejects an in-flight callback');
});
