const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
test('guest confirmation and unsubscribe roundtrip, replay, expired and invalid tokens',{skip:process.env.SUBSCRIPTION_INTEGRATION!=='true'},async t=>{
const name='mooncci_qa_subscription_'+process.pid;
Object.assign(process.env,{DB_HOST:'127.0.0.1',DB_PORT:process.env.TEST_DB_PORT||'33079',DB_USER:'root',DB_PASSWORD:'',DB_NAME:name,JWT_SECRET:'subscription-local-test-only-secret',SITE_URL:'https://mooncci.site',NEWSLETTER_DELIVERY_ENABLED:'true'});
const setup=await require('mysql2/promise').createConnection({host:'127.0.0.1',port:Number(process.env.TEST_DB_PORT||33079),user:'root',multipleStatements:true});
await setup.query('CREATE DATABASE '+name+' CHARACTER SET utf8mb4');await setup.query('USE '+name);await setup.query(fs.readFileSync(path.join(__dirname,'../database/schema.sql'),'utf8'));
const db=require('../src/db'),platform=require('../src/platformDb');
const config={enabled:'true',smtp_host:'example.invalid',smtp_user:'news@example.test',smtp_pass:'fake',smtp_from:'news@example.test'};
await db.query('INSERT INTO site_settings(setting_key,setting_value) VALUES (?,?)',['mail',JSON.stringify(config)]);
const sent=[];t.mock.method(require('nodemailer'),'createTransport',()=>({sendMail:async m=>{sent.push(m);return {accepted:[m.to]};}}));
const app=require('express')();app.set('trust proxy','loopback');app.use(require('express').json());app.use('/api',require('../src/routes/subscriptions').router);
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
t.after(async()=>{await new Promise(r=>server.close(r));await db.end();await platform.end();await setup.query('DROP DATABASE '+name);await setup.end();});
let seq=1;const call=async(action,body)=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/subscriptions'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Forwarded-For':'192.0.2.'+seq++},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
assert.equal((await call('',{email:'reader@example.test'})).status,200);
const mail=sent[0];assert.match(mail.html,/取消订阅（无需登录）/);
const confirm=mail.text.match(/\/confirm#([a-f0-9]{64})/)[1],unsub=mail.text.match(/\/unsubscribe#([a-f0-9]{64})/)[1];
assert.notEqual(confirm,unsub);
let r=await call('/confirm',{token:confirm});assert.equal(r.status,200);assert.match(r.data.message,/成功订阅 mooncci 周报/);
assert.equal((await call('/confirm',{token:confirm})).status,200);
assert.equal((await call('/unsubscribe',{token:'f'.repeat(64)})).status,400);
assert.equal((await call('/unsubscribe',{token:unsub})).status,200);
assert.equal((await call('/unsubscribe',{token:unsub})).status,200);
assert.equal((await call('/confirm',{token:confirm})).status,400);
let [[row]]=await platform.query('SELECT status,confirm_hash FROM subscribers WHERE email=?',['reader@example.test']);assert.equal(row.status,'unsubscribed');assert.equal(row.confirm_hash,null);
await call('',{email:'pending@example.test'});const pending=sent[1].text.match(/\/unsubscribe#([a-f0-9]{64})/)[1];assert.equal((await call('/unsubscribe',{token:pending})).status,200);
await platform.query('UPDATE newsletter_tokens SET expires_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY)');assert.equal((await call('/unsubscribe',{token:unsub})).status,400);
assert.equal((await call('/confirm',{token:'bad'})).status,400);
});
